# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed846678ce4fea77e75911e963a52dd9aaae4a6e645f76d71aa28b174720e1d2d390062154f9586f32e6c93778cf3335e76f63091ed26ce834f5ba548bb502ed

test:
  secret_key_base: f932debfb91fbdd6d3ab643ae92604f2ec476ca48d0820c782da91e2625618fe805d0f53ea2a19298a3ff5d3c6b73d75c3a2f89673856817ade5e0d5a011989b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
